/* =========================================================================
   RaktárBázis — KAMU ADATBÁZIS (frontend-only demo)
   Minden adat a böngészőben él; a localStorage-ban marad meg módosítás után.
   ========================================================================= */

// ---- Szállítók (csak a FŐNÖK látja) ----
const SUPPLIERS = [
  { id: "s1", name: "VillVill Szakáruház",      site: "villvill.hu" },
  { id: "s2", name: "Gépész Szakbolt",           site: "gepeszbolt.hu" },
  { id: "s3", name: "Építőanyag Kereskedés",     site: "epitoanyag.hu" },
];

// ---- Felhasználók (demo) ----
const USERS = [
  { id: "b1", name: "Nagy Gábor",     role: "boss",   email: "gabor@ceg.hu" },
  { id: "b2", name: "Kiss Andrea",    role: "boss",   email: "andrea@ceg.hu" },
  { id: "b3", name: "Tóth Péter",     role: "boss",   email: "peter@ceg.hu" },
  { id: "b4", name: "Szabó Éva",      role: "boss",   email: "eva@ceg.hu" },
  { id: "b5", name: "Varga Zoltán",   role: "boss",   email: "zoltan@ceg.hu" },
  { id: "b6", name: "Farkas Imre",    role: "boss",   email: "imre@ceg.hu" },
  { id: "w1", name: "Molnár Bence",   role: "worker", email: "bence@ceg.hu" },
  { id: "w2", name: "Horváth Dávid",  role: "worker", email: "david@ceg.hu" },
  { id: "w3", name: "Balogh Martin",  role: "worker", email: "martin@ceg.hu" },
  { id: "w4", name: "Németh Ádám",    role: "worker", email: "adam@ceg.hu" },
  { id: "w5", name: "Oláh Krisztián", role: "worker", email: "krisztian@ceg.hu" },
  { id: "w6", name: "Papp Levente",   role: "worker", email: "levente@ceg.hu" },
  { id: "w7", name: "Simon Tamás",    role: "worker", email: "tamas@ceg.hu" },
  { id: "w8", name: "Fehér Gergő",    role: "worker", email: "gergo@ceg.hu" },
  { id: "w9", name: "Kovács Róbert",  role: "worker", email: "robert@ceg.hu" },
  { id: "w10", name: "Lakatos Márk",  role: "worker", email: "mark@ceg.hu" },
  { id: "w11", name: "Takács Norbert", role: "worker", email: "norbert@ceg.hu" },
  { id: "w12", name: "Bíró Patrik",   role: "worker", email: "patrik@ceg.hu" },
];

// ---- Kiinduló katalógus ----
// cat: villany | gepesz | komuves | egyeb
// unit: db | m | csomag | doboz | kg | l | tekercs | pár
// tool=true -> csak 0 készletnél jelez riasztást
const SEED_ITEMS = [
  // ================= VILLANYSZERELŐ =================
  { name: "Wago 221-412 csattos kötőelem (2 vezetékes)", aliases: ["wagó 2-es", "wago csattos 2", "wago 221", "kétvezetékes wagó"], sku: "221-412", cat: "villany", unit: "db", qty: 210, min: 80, tool: false, loc: "erno", sup: "s1", emoji: "🔌" },
  { name: "Wago 221-413 csattos kötőelem (3 vezetékes)", aliases: ["wagó 3-as", "wago csattos 3", "háromvezetékes wagó", "wagó"], sku: "221-413", cat: "villany", unit: "db", qty: 54, min: 80, tool: false, loc: "erno", sup: "s1", emoji: "🔌" },
  { name: "Wago 221-415 csattos kötőelem (5 vezetékes)", aliases: ["wagó 5-ös", "wago csattos 5", "ötvezetékes wagó"], sku: "221-415", cat: "villany", unit: "db", qty: 0, min: 40, tool: false, loc: "erno", sup: "s1", emoji: "🔌" },
  { name: "Wago 2273-202 bedugós kötőelem (2 vezetékes)", aliases: ["wagó bedugós 2", "wago 2273", "szorítós wagó 2"], sku: "2273-202", cat: "villany", unit: "db", qty: 140, min: 60, tool: false, loc: "kalvaria", sup: "s1", emoji: "🔌" },
  { name: "Wago 2273-203 bedugós kötőelem (3 vezetékes)", aliases: ["wagó bedugós 3", "szorítós wagó 3"], sku: "2273-203", cat: "villany", unit: "db", qty: 22, min: 60, tool: false, loc: "kalvaria", sup: "s1", emoji: "🔌" },
  { name: "Érvéghüvely 0,75 mm²", aliases: ["érvéghüvely 0.75", "hüvely 0.75", "saru 0.75"], sku: "EH-075", cat: "villany", unit: "csomag", qty: 8, min: 10, tool: false, loc: "erno", sup: "s1", emoji: "🔗" },
  { name: "Érvéghüvely 1,5 mm²", aliases: ["érvéghüvely 1.5", "hüvely 1.5"], sku: "EH-150", cat: "villany", unit: "csomag", qty: 15, min: 10, tool: false, loc: "erno", sup: "s1", emoji: "🔗" },
  { name: "Érvéghüvely 2,5 mm²", aliases: ["érvéghüvely 2.5", "hüvely 2.5"], sku: "EH-250", cat: "villany", unit: "csomag", qty: 5, min: 10, tool: false, loc: "kalvaria", sup: "s1", emoji: "🔗" },
  { name: "Érvéghüvely nyomó fogó", aliases: ["érvéghüvely nyomó", "hüvely nyomó", "krimpelő"], sku: "EH-PRESS", cat: "villany", unit: "db", qty: 3, min: 1, tool: true, loc: "erno", sup: "s1", emoji: "🛠️" },
  { name: "Kismegszakító 6A B 1P", aliases: ["6A kismegszakító", "6 amperes megszakító", "B6"], sku: "MCB-B6", cat: "villany", unit: "db", qty: 12, min: 6, tool: false, loc: "erno", sup: "s1", emoji: "⚡" },
  { name: "Kismegszakító 10A B 1P", aliases: ["10A kismegszakító", "10 amperes megszakító", "B10"], sku: "MCB-B10", cat: "villany", unit: "db", qty: 18, min: 6, tool: false, loc: "erno", sup: "s1", emoji: "⚡" },
  { name: "Kismegszakító 16A B 1P", aliases: ["16A kismegszakító", "16 amperes megszakító", "B16", "kismegszakító 16"], sku: "MCB-B16", cat: "villany", unit: "db", qty: 7, min: 10, tool: false, loc: "kalvaria", sup: "s1", emoji: "⚡" },
  { name: "Kismegszakító 16A C 1P", aliases: ["16A C kismegszakító", "C16", "C karakterisztikás 16A"], sku: "MCB-C16", cat: "villany", unit: "db", qty: 11, min: 6, tool: false, loc: "erno", sup: "s1", emoji: "⚡" },
  { name: "Kismegszakító 16A B 3P", aliases: ["16A 3P kismegszakító", "3 fázisú 16A", "hárompólusú megszakító"], sku: "MCB-B16-3P", cat: "villany", unit: "db", qty: 4, min: 4, tool: false, loc: "kalvaria", sup: "s1", emoji: "⚡" },
  { name: "MBCu 3x1,5 rézkábel", aliases: ["mbcu 3x1.5", "kábel 3x1.5", "3x1.5 kábel"], sku: "MBCU-3X15", cat: "villany", unit: "m", qty: 120, min: 50, tool: false, loc: "erno", sup: "s1", emoji: "🧵" },
  { name: "MBCu 3x2,5 rézkábel", aliases: ["mbcu 3x2.5", "kábel 3x2.5", "3x2.5 kábel", "mbcu"], sku: "MBCU-3X25", cat: "villany", unit: "m", qty: 23, min: 50, tool: false, loc: "kalvaria", sup: "s1", emoji: "🧵" },
  { name: "H07V-U 1,5 mm² vezeték", aliases: ["mcu 1.5", "vezeték 1.5", "1.5-ös vezeték"], sku: "H07VU-15", cat: "villany", unit: "m", qty: 200, min: 80, tool: false, loc: "erno", sup: "s1", emoji: "🧵" },
  { name: "H07V-U 2,5 mm² vezeték", aliases: ["mcu 2.5", "vezeték 2.5", "2.5-ös vezeték"], sku: "H07VU-25", cat: "villany", unit: "m", qty: 90, min: 60, tool: false, loc: "kalvaria", sup: "s1", emoji: "🧵" },
  { name: "Szigetelőszalag", aliases: ["szigszalag", "iso szalag", "szigetelő szalag"], sku: "ISO-19", cat: "villany", unit: "db", qty: 26, min: 10, tool: false, loc: "erno", sup: "s1", emoji: "🎗️" },
  { name: "Dugalj süllyesztett", aliases: ["dugalj", "konnektor", "aljzat"], sku: "DUG-S", cat: "villany", unit: "db", qty: 14, min: 8, tool: false, loc: "erno", sup: "s1", emoji: "🔌" },
  { name: "Kapcsoló váltó", aliases: ["kapcsoló", "váltókapcsoló"], sku: "KAP-V", cat: "villany", unit: "db", qty: 9, min: 6, tool: false, loc: "kalvaria", sup: "s1", emoji: "🎚️" },
  { name: "LED izzó E27", aliases: ["izzó", "led izzó", "körte", "égő"], sku: "LED-E27", cat: "villany", unit: "db", qty: 20, min: 12, tool: false, loc: "erno", sup: "s1", emoji: "💡" },
  { name: "Multiméter", aliases: ["multiméter", "műszer", "volt mérő"], sku: "MM-100", cat: "villany", unit: "db", qty: 2, min: 1, tool: true, loc: "erno", sup: "s1", emoji: "📟" },
  { name: "Fázisceruza", aliases: ["fázisceruza", "fáziskereső", "ceruza"], sku: "FZ-1", cat: "villany", unit: "db", qty: 6, min: 2, tool: true, loc: "kalvaria", sup: "s1", emoji: "🖊️" },
  { name: "Kombinált fogó", aliases: ["kombinált fogó", "fogó", "kombi fogó"], sku: "KF-180", cat: "villany", unit: "db", qty: 5, min: 2, tool: true, loc: "erno", sup: "s1", emoji: "🔧" },
  { name: "Csavarhúzó készlet (VDE)", aliases: ["csavarhúzó", "csavarhúzó készlet", "vde készlet"], sku: "CSH-VDE", cat: "villany", unit: "db", qty: 4, min: 2, tool: true, loc: "kalvaria", sup: "s1", emoji: "🪛" },
  { name: "Teleszkópos nyél", aliases: ["tediszár", "tediszér", "teleszkópos", "hosszítható nyél", "tedi"], sku: "TN-400", cat: "villany", unit: "db", qty: 3, min: 2, tool: true, loc: "erno", sup: "s1", emoji: "📏" },
  { name: "Sorkapocs (lüszter) 3P", aliases: ["sorkapocs", "lüszter", "kötőkapocs"], sku: "SK-3P", cat: "villany", unit: "db", qty: 30, min: 15, tool: false, loc: "erno", sup: "s1", emoji: "🧲" },
  { name: "Vezetékcsatorna 20x10", aliases: ["vezetékcsatorna", "kábelcsatorna", "vcc"], sku: "VCS-2010", cat: "villany", unit: "m", qty: 40, min: 20, tool: false, loc: "kalvaria", sup: "s1", emoji: "📐" },

  // ================= GÉPÉSZ =================
  { name: "GEBO javító bilincs 1/2\"", aliases: ["gebó 1/2", "gebo bilincs", "csőjavító bilincs", "gebó"], sku: "GEBO-12", cat: "gepesz", unit: "db", qty: 9, min: 10, tool: false, loc: "erno", sup: "s2", emoji: "⭕" },
  { name: "GEBO javító bilincs 3/4\"", aliases: ["gebó 3/4", "gebo bilincs 3/4"], sku: "GEBO-34", cat: "gepesz", unit: "db", qty: 12, min: 10, tool: false, loc: "erno", sup: "s2", emoji: "⭕" },
  { name: "GEBO javító bilincs 1\"", aliases: ["gebó 1", "gebo bilincs 1"], sku: "GEBO-100", cat: "gepesz", unit: "db", qty: 2, min: 8, tool: false, loc: "kalvaria", sup: "s2", emoji: "⭕" },
  { name: "Teflonszalag", aliases: ["teflon", "tömítőszalag", "teflonszalag"], sku: "TEF-12", cat: "gepesz", unit: "db", qty: 18, min: 8, tool: false, loc: "erno", sup: "s2", emoji: "🎗️" },
  { name: "Kender (tömítő)", aliases: ["kender", "tömítőkender"], sku: "KEN-100", cat: "gepesz", unit: "csomag", qty: 6, min: 4, tool: false, loc: "erno", sup: "s2", emoji: "🌾" },
  { name: "O-gyűrű készlet", aliases: ["o gyűrű", "o-gyűrű", "tömítőgyűrű"], sku: "OR-KIT", cat: "gepesz", unit: "doboz", qty: 3, min: 2, tool: false, loc: "kalvaria", sup: "s2", emoji: "⭕" },
  { name: "Flexibilis csatlakozó 1/2\"", aliases: ["flexi cső", "gégecső", "flexibilis"], sku: "FLX-12", cat: "gepesz", unit: "db", qty: 7, min: 6, tool: false, loc: "erno", sup: "s2", emoji: "🐍" },
  { name: "Mosdó szifon", aliases: ["szifon", "bűzelzáró"], sku: "SZIF-32", cat: "gepesz", unit: "db", qty: 5, min: 3, tool: false, loc: "kalvaria", sup: "s2", emoji: "🌀" },
  { name: "Csaptelep tömítés készlet", aliases: ["csaptelep tömítés", "csap tömítés"], sku: "CSAP-TK", cat: "gepesz", unit: "csomag", qty: 8, min: 4, tool: false, loc: "erno", sup: "s2", emoji: "🔩" },
  { name: "Csőfogó", aliases: ["csőfogó", "vízpumpafogó"], sku: "CSF-250", cat: "gepesz", unit: "db", qty: 4, min: 2, tool: true, loc: "kalvaria", sup: "s2", emoji: "🔧" },
  { name: "Svédkulcs", aliases: ["svédkulcs", "franciakulcs", "állítható kulcs"], sku: "SVK-200", cat: "gepesz", unit: "db", qty: 5, min: 2, tool: true, loc: "erno", sup: "s2", emoji: "🔧" },
  { name: "Csővágó", aliases: ["csővágó", "rézcső vágó"], sku: "CSV-35", cat: "gepesz", unit: "db", qty: 2, min: 1, tool: true, loc: "kalvaria", sup: "s2", emoji: "✂️" },
  { name: "Menetvágó készlet", aliases: ["menetvágó", "menetfúró"], sku: "MV-KIT", cat: "gepesz", unit: "db", qty: 1, min: 1, tool: true, loc: "erno", sup: "s2", emoji: "🛠️" },
  { name: "WD-40 kenőspray", aliases: ["wd40", "wd 40", "rozsdaoldó", "kenő spray"], sku: "WD40-300", cat: "gepesz", unit: "db", qty: 11, min: 5, tool: false, loc: "erno", sup: "s2", emoji: "🧴" },
  { name: "Gépzsír", aliases: ["zsír", "kenőzsír", "gépzsír"], sku: "ZSIR-400", cat: "gepesz", unit: "kg", qty: 4, min: 2, tool: false, loc: "kalvaria", sup: "s2", emoji: "🛢️" },
  { name: "Univerzális olaj", aliases: ["olaj", "gép olaj"], sku: "OLAJ-1L", cat: "gepesz", unit: "l", qty: 6, min: 3, tool: false, loc: "erno", sup: "s2", emoji: "🛢️" },
  { name: "Saniter szilikon", aliases: ["sziló", "szilikon", "szaniter szilikon"], sku: "SZIL-300", cat: "gepesz", unit: "db", qty: 13, min: 6, tool: false, loc: "kalvaria", sup: "s2", emoji: "🧪" },
  { name: "Fém csőbilincs", aliases: ["csőbilincs", "bilincs"], sku: "CSB-20", cat: "gepesz", unit: "db", qty: 40, min: 15, tool: false, loc: "erno", sup: "s2", emoji: "⭕" },
  { name: "Szorítógyűrű", aliases: ["szorítógyűrű", "seeger gyűrű"], sku: "SZGYR-KIT", cat: "gepesz", unit: "doboz", qty: 4, min: 2, tool: false, loc: "kalvaria", sup: "s2", emoji: "⭕" },
  { name: "Kétkomponensű ragasztó", aliases: ["kétkomponensű ragasztó", "2k ragasztó", "epoxi"], sku: "2K-RAG", cat: "gepesz", unit: "db", qty: 6, min: 3, tool: false, loc: "erno", sup: "s2", emoji: "🧪" },
  { name: "Csapágy 6204", aliases: ["csapágy", "6204"], sku: "CSAP-6204", cat: "gepesz", unit: "db", qty: 5, min: 2, tool: false, loc: "kalvaria", sup: "s2", emoji: "⚙️" },
  { name: "Ékszíj", aliases: ["ékszíj", "szíj"], sku: "EKSZ-13", cat: "gepesz", unit: "db", qty: 3, min: 2, tool: false, loc: "erno", sup: "s2", emoji: "🔄" },
  { name: "Csavar/anya/alátét készlet", aliases: ["csavar készlet", "anya csavar", "kötőelem készlet"], sku: "CSAV-KIT", cat: "gepesz", unit: "doboz", qty: 5, min: 2, tool: false, loc: "kalvaria", sup: "s2", emoji: "🔩" },
  { name: "Imbusz kulcs készlet", aliases: ["imbusz", "imbusz kulcs", "hatlapfejű kulcs"], sku: "IMB-KIT", cat: "gepesz", unit: "db", qty: 6, min: 2, tool: true, loc: "erno", sup: "s2", emoji: "🔧" },
  { name: "Akkus fúró-csavarozó", aliases: ["fúró", "akkus fúró", "csavarozó"], sku: "AK-FURO", cat: "gepesz", unit: "db", qty: 2, min: 1, tool: true, loc: "kalvaria", sup: "s2", emoji: "🔩" },

  // ================= KŐMŰVES =================
  { name: "Glett (20 kg)", aliases: ["glett", "glettelő", "gipsz"], sku: "GLETT-20", cat: "komuves", unit: "kg", qty: 60, min: 40, tool: false, loc: "erno", sup: "s3", emoji: "🧱" },
  { name: "Glettvas", aliases: ["glettvas", "spakli"], sku: "GLV-25", cat: "komuves", unit: "db", qty: 4, min: 2, tool: true, loc: "erno", sup: "s3", emoji: "🔧" },
  { name: "Javítóhabarcs (25 kg)", aliases: ["javítóhabarcs", "habarcs", "javító vakolat"], sku: "JH-25", cat: "komuves", unit: "kg", qty: 75, min: 50, tool: false, loc: "kalvaria", sup: "s3", emoji: "🧱" },
  { name: "Csemperagasztó (25 kg)", aliases: ["csemperagasztó", "csempe ragasztó"], sku: "CSR-25", cat: "komuves", unit: "kg", qty: 50, min: 50, tool: false, loc: "erno", sup: "s3", emoji: "🧱" },
  { name: "Fugázó (5 kg)", aliases: ["fugázó", "fuga"], sku: "FUG-5", cat: "komuves", unit: "kg", qty: 15, min: 10, tool: false, loc: "kalvaria", sup: "s3", emoji: "🧱" },
  { name: "Tipli 6 mm", aliases: ["tipli 6", "dübel 6", "műanyag tipli"], sku: "TIP-6", cat: "komuves", unit: "doboz", qty: 12, min: 6, tool: false, loc: "erno", sup: "s3", emoji: "🔩" },
  { name: "Tipli 8 mm", aliases: ["tipli 8", "dübel 8"], sku: "TIP-8", cat: "komuves", unit: "doboz", qty: 9, min: 6, tool: false, loc: "kalvaria", sup: "s3", emoji: "🔩" },
  { name: "Univerzális csavar készlet", aliases: ["csavar", "facscavar", "univerzális csavar"], sku: "CSAV-U", cat: "komuves", unit: "doboz", qty: 7, min: 4, tool: false, loc: "erno", sup: "s3", emoji: "🔩" },
  { name: "Mérőszalag 5 m", aliases: ["mérőszalag", "centi", "mérő"], sku: "MER-5", cat: "komuves", unit: "db", qty: 8, min: 3, tool: true, loc: "kalvaria", sup: "s3", emoji: "📏" },
  { name: "Vízmérték (libella) 60 cm", aliases: ["vízmérték", "libella", "szintező"], sku: "VM-60", cat: "komuves", unit: "db", qty: 3, min: 1, tool: true, loc: "erno", sup: "s3", emoji: "📐" },
  { name: "Kalapács", aliases: ["kalapács"], sku: "KAL-300", cat: "komuves", unit: "db", qty: 5, min: 2, tool: true, loc: "kalvaria", sup: "s3", emoji: "🔨" },
  { name: "Véső", aliases: ["véső", "laposvéső"], sku: "VES-250", cat: "komuves", unit: "db", qty: 4, min: 2, tool: true, loc: "erno", sup: "s3", emoji: "🔨" },
  { name: "Spakli készlet", aliases: ["spakli készlet", "spakli"], sku: "SPA-KIT", cat: "komuves", unit: "db", qty: 4, min: 2, tool: true, loc: "kalvaria", sup: "s3", emoji: "🛠️" },
  { name: "Simító", aliases: ["simító", "glettvas nagy"], sku: "SIM-30", cat: "komuves", unit: "db", qty: 3, min: 1, tool: true, loc: "erno", sup: "s3", emoji: "🛠️" },
  { name: "Csiszolóvászon", aliases: ["csiszolóvászon", "smirgli", "csiszolópapír"], sku: "CSVZ-P120", cat: "komuves", unit: "db", qty: 40, min: 20, tool: false, loc: "kalvaria", sup: "s3", emoji: "🧽" },
  { name: "Aljzatkiegyenlítő (25 kg)", aliases: ["aljzatkiegyenlítő", "önterülő", "aljzat"], sku: "AK-25", cat: "komuves", unit: "kg", qty: 25, min: 25, tool: false, loc: "erno", sup: "s3", emoji: "🧱" },

  // ================= EGYÉB =================
  { name: "Diszperziós falfesték fehér (10 l)", aliases: ["falfesték", "diszperzit", "fehér festék"], sku: "DF-10L", cat: "egyeb", unit: "l", qty: 30, min: 15, tool: false, loc: "erno", sup: "s3", emoji: "🖌️" },
  { name: "Zománcfesték (0,75 l)", aliases: ["zománc", "zománcfesték"], sku: "ZOM-075", cat: "egyeb", unit: "l", qty: 4, min: 3, tool: false, loc: "kalvaria", sup: "s3", emoji: "🖌️" },
  { name: "Alapozó (10 l)", aliases: ["alapozó", "mélyalapozó"], sku: "ALAP-10", cat: "egyeb", unit: "l", qty: 12, min: 10, tool: false, loc: "erno", sup: "s3", emoji: "🖌️" },
  { name: "Hígító", aliases: ["hígító", "oldószer"], sku: "HIG-1L", cat: "egyeb", unit: "l", qty: 5, min: 3, tool: false, loc: "kalvaria", sup: "s3", emoji: "🧴" },
  { name: "Maszkolószalag", aliases: ["maszkoló", "festőszalag", "ragasztószalag papír"], sku: "MAS-30", cat: "egyeb", unit: "db", qty: 15, min: 8, tool: false, loc: "erno", sup: "s3", emoji: "🎗️" },
  { name: "Festőhenger", aliases: ["festőhenger", "henger", "mázoló henger"], sku: "FH-18", cat: "egyeb", unit: "db", qty: 6, min: 3, tool: true, loc: "kalvaria", sup: "s3", emoji: "🖌️" },
  { name: "Ecset készlet", aliases: ["ecset", "ecset készlet", "mázoló ecset"], sku: "ECS-KIT", cat: "egyeb", unit: "db", qty: 5, min: 2, tool: true, loc: "erno", sup: "s3", emoji: "🖌️" },
  { name: "Munkakesztyű", aliases: ["kesztyű", "munkakesztyű", "munkás kesztyű"], sku: "MK-10", cat: "egyeb", unit: "pár", qty: 30, min: 15, tool: false, loc: "kalvaria", sup: "s3", emoji: "🧤" },
  { name: "Védőszemüveg", aliases: ["szemüveg", "védőszemüveg", "védő okulár"], sku: "VSZ-1", cat: "egyeb", unit: "db", qty: 8, min: 4, tool: false, loc: "erno", sup: "s3", emoji: "🥽" },
  { name: "Pillanatragasztó", aliases: ["pillanatragasztó", "szuperragasztó", "cyanoakrilát"], sku: "PR-3", cat: "egyeb", unit: "db", qty: 10, min: 5, tool: false, loc: "kalvaria", sup: "s3", emoji: "🧪" },
  { name: "Építési ragasztó", aliases: ["építési ragasztó", "montázsragasztó", "szerelőragasztó"], sku: "ER-300", cat: "egyeb", unit: "db", qty: 7, min: 4, tool: false, loc: "erno", sup: "s3", emoji: "🧪" },
  { name: "Univerzális takarítószer", aliases: ["takarítószer", "tisztítószer"], sku: "TAK-1L", cat: "egyeb", unit: "l", qty: 8, min: 4, tool: false, loc: "kalvaria", sup: "s3", emoji: "🧴" },
  { name: "Szemeteszsák (120 l)", aliases: ["szemeteszsák", "kukazsák", "zsák"], sku: "SZSZ-120", cat: "egyeb", unit: "db", qty: 60, min: 25, tool: false, loc: "erno", sup: "s3", emoji: "🗑️" },

  // === kutatásból: villany ===
  { name: "Wago 2273-205 bedugós kötőelem (5 vezetékes)", aliases: ["wagó bedugós 5", "wago 2273 5", "szorítós wagó 5"], sku: "2273-205", cat: "villany", unit: "db", qty: 30, min: 20, tool: false, loc: "kalvaria", sup: "s1", emoji: "🔌" },
  { name: "LED spot GU10", aliases: ["spot", "spot égő", "gu10", "spotlámpa izzó"], sku: "LED-GU10", cat: "villany", unit: "db", qty: 15, min: 10, tool: false, loc: "erno", sup: "s1", emoji: "💡" },
  { name: "FI-relé (áram-védőkapcsoló) 2P 25A 30mA", aliases: ["fi relé", "fi", "áramvédő", "életvédő kapcsoló", "fi-relé"], sku: "FI-2P25", cat: "villany", unit: "db", qty: 2, min: 1, tool: false, loc: "erno", sup: "s1", emoji: "⚡" },
  { name: "Műanyag kötődoboz IP54", aliases: ["kötődoboz", "elágazó doboz", "doboz"], sku: "KD-IP54", cat: "villany", unit: "db", qty: 18, min: 8, tool: false, loc: "kalvaria", sup: "s1", emoji: "📦" },
  { name: "PVC védőcső (gegecső)", aliases: ["gegecső", "hullámcső", "védőcső", "flex cső"], sku: "GEG-20", cat: "villany", unit: "m", qty: 60, min: 25, tool: false, loc: "erno", sup: "s1", emoji: "🐍" },
  { name: "Tipli + facsavar szerelőkészlet", aliases: ["tipli", "dübel", "facsavar", "szerelőkészlet"], sku: "TIPL-KIT", cat: "villany", unit: "csomag", qty: 10, min: 4, tool: false, loc: "erno", sup: "s3", emoji: "🔩" },
  { name: "Süllyesztett szerelvénydoboz", aliases: ["szerelődoboz", "aljzatdoboz", "szerelvénydoboz"], sku: "SZDB-68", cat: "villany", unit: "db", qty: 25, min: 12, tool: false, loc: "kalvaria", sup: "s1", emoji: "📦" },
  { name: "Kétpólusú feszültségvizsgáló (DUSPOL)", aliases: ["duspol", "feszültségvizsgáló", "kétpólusú ceruza", "feszültségmérő"], sku: "DUSPOL-1", cat: "villany", unit: "db", qty: 2, min: 1, tool: true, loc: "erno", sup: "s1", emoji: "🖊️" },
  { name: "Oldalcsípő fogó", aliases: ["csípőfogó", "oldalcsípő", "csípő"], sku: "OCS-160", cat: "villany", unit: "db", qty: 4, min: 2, tool: true, loc: "kalvaria", sup: "s1", emoji: "🔧" },
  { name: "Villanyszerelő kés (kábeltörő)", aliases: ["kábeltörő", "szerelő kés", "szigeteléslehúzó"], sku: "VK-1", cat: "villany", unit: "db", qty: 3, min: 2, tool: true, loc: "erno", sup: "s1", emoji: "🔪" },

  // === kutatásból: gépész ===
  { name: "GEBO MB kétrészes javító bilincs (kimenetes)", aliases: ["gebó leágazó", "gebo mb", "javító bilincs kimenet"], sku: "GEBO-MB-28", cat: "gepesz", unit: "db", qty: 3, min: 2, tool: false, loc: "erno", sup: "s2", emoji: "⭕" },
  { name: "Menettömítő paszta (Tangit)", aliases: ["tangit", "menetpaszta", "tömítőpaszta"], sku: "TANG-100", cat: "gepesz", unit: "db", qty: 5, min: 3, tool: false, loc: "erno", sup: "s2", emoji: "🧴" },
  { name: "Loctite 55 menettömítő zsinór", aliases: ["loctite 55", "menettömítő zsinór", "loctite"], sku: "LOC-55", cat: "gepesz", unit: "db", qty: 4, min: 3, tool: false, loc: "kalvaria", sup: "s2", emoji: "🧵" },
  { name: "Golyóscsap 1/2\"", aliases: ["golyóscsap", "gömbcsap", "olasz csap", "elzáró csap"], sku: "GCS-12", cat: "gepesz", unit: "db", qty: 8, min: 6, tool: false, loc: "erno", sup: "s2", emoji: "🚰" },
  { name: "Kerámia csaptelep betét", aliases: ["csapbetét", "kerámia betét", "kazetta"], sku: "CSB-35", cat: "gepesz", unit: "db", qty: 6, min: 4, tool: false, loc: "kalvaria", sup: "s2", emoji: "⚙️" },
  { name: "Perlátor (sugárszabályzó)", aliases: ["perlátor", "sugárszabályzó", "szűrőbetét"], sku: "PER-M24", cat: "gepesz", unit: "db", qty: 5, min: 4, tool: false, loc: "erno", sup: "s2", emoji: "💧" },
  { name: "Fagyálló/hűtőfolyadék", aliases: ["fagyálló", "hűtőfolyadék", "antifriz"], sku: "FAGY-1L", cat: "gepesz", unit: "l", qty: 12, min: 8, tool: false, loc: "erno", sup: "s2", emoji: "🧴" },
  { name: "Fűtési inhibitor", aliases: ["inhibitor", "fűtésvíz adalék"], sku: "INH-1L", cat: "gepesz", unit: "l", qty: 4, min: 2, tool: false, loc: "kalvaria", sup: "s2", emoji: "🧪" },
  { name: "Szivattyú tengelytömítés (szimmering)", aliases: ["szimmering", "tengelytömítés", "szivattyú tömítés"], sku: "SZIM-KIT", cat: "gepesz", unit: "db", qty: 3, min: 2, tool: false, loc: "erno", sup: "s2", emoji: "⚙️" },
  { name: "PE csőhéj szigetelés", aliases: ["csőhéj", "hőszigetelés", "csőszigetelés"], sku: "PEH-22", cat: "gepesz", unit: "m", qty: 25, min: 30, tool: false, loc: "kalvaria", sup: "s2", emoji: "🧻" },
  { name: "Villáskulcs készlet", aliases: ["villáskulcs", "kulcs készlet", "kulcskészlet"], sku: "VK-KIT", cat: "gepesz", unit: "db", qty: 3, min: 1, tool: true, loc: "erno", sup: "s2", emoji: "🔧" },
  { name: "Vízpumpa fogó", aliases: ["pumpafogó", "vízpumpafogó"], sku: "PF-250", cat: "gepesz", unit: "db", qty: 4, min: 2, tool: true, loc: "kalvaria", sup: "s2", emoji: "🔧" },
  { name: "Sarokcsiszoló (flex)", aliases: ["flex", "sarokcsiszoló"], sku: "FLEX-125", cat: "gepesz", unit: "db", qty: 2, min: 1, tool: true, loc: "erno", sup: "s2", emoji: "⚙️" },
  { name: "Ütvefúró", aliases: ["fúró", "ütvefúró", "fúrógép"], sku: "UF-600", cat: "gepesz", unit: "db", qty: 2, min: 1, tool: true, loc: "kalvaria", sup: "s2", emoji: "🔩" },

  // === kutatásból: kőműves / egyéb ===
  { name: "Akril tömítő", aliases: ["akril", "festhető tömítő", "akril tömítő"], sku: "AKR-300", cat: "komuves", unit: "db", qty: 9, min: 5, tool: false, loc: "erno", sup: "s3", emoji: "🧪" },
  { name: "Hypo (klór)", aliases: ["hypo", "klór", "nátrium hipoklorit"], sku: "HYPO-1L", cat: "egyeb", unit: "l", qty: 6, min: 4, tool: false, loc: "kalvaria", sup: "s3", emoji: "🧴" },
  { name: "Ablaktisztító", aliases: ["ablaktisztító", "üvegtisztító", "ablakmosó"], sku: "ABL-1L", cat: "egyeb", unit: "l", qty: 5, min: 3, tool: false, loc: "erno", sup: "s3", emoji: "🧴" },
  { name: "Porvédő maszk FFP2", aliases: ["ffp2", "pormaszk", "porvédő maszk", "maszk"], sku: "FFP2-1", cat: "egyeb", unit: "db", qty: 25, min: 20, tool: false, loc: "kalvaria", sup: "s3", emoji: "😷" },
  { name: "Mikroszálas kendő", aliases: ["mikroszálas", "törlőkendő", "rongy"], sku: "MK-1", cat: "egyeb", unit: "db", qty: 20, min: 10, tool: false, loc: "erno", sup: "s3", emoji: "🧻" },
];

// ---- átmenetileg elrejtett elemek (a képük nem lett jó; később visszatehetők) ----
const HIDDEN_ITEMS = [
  "FI-relé (áram-védőkapcsoló) 2P 25A 30mA",
  "Glettvas",
  "Gépzsír",
  "Szivattyú tengelytömítés (szimmering)",
  "Teleszkópos nyél",
  "Sorkapocs (lüszter) 3P",
  "Vezetékcsatorna 20x10",
  "Ékszíj",
  "Porvédő maszk FFP2",
  "Védőszemüveg",
  "Érvéghüvely 0,75 mm²",
  "Érvéghüvely 1,5 mm²",
];

// ---- a lista végére kerülő elemek (ne látszódjanak rögtön nyitáskor) ----
const LAST_ITEMS = [
];

// ---- méret/jelölés címke a képre (hogy látszódjon, melyik milyen) ----
const SIZE_LABELS = {
  "MBCu 3x1,5 rézkábel": "3×1,5",
  "MBCu 3x2,5 rézkábel": "3×2,5",
  "H07V-U 1,5 mm² vezeték": "1,5",
  "H07V-U 2,5 mm² vezeték": "2,5",
  "Tipli 6 mm": "6 mm",
  "Tipli 8 mm": "8 mm",
};

// ---- valódi, átlátszó hátterű termékképek (név -> fájl) ----
const ITEM_IMAGES = {
  "Wago 221-412 csattos kötőelem (2 vezetékes)": "images/wago-221-412.png",
  "Wago 221-413 csattos kötőelem (3 vezetékes)": "images/wago-221-413.png",
  "Wago 221-415 csattos kötőelem (5 vezetékes)": "images/wago-221-415.png",
  "Wago 2273-202 bedugós kötőelem (2 vezetékes)": "images/wago-2273-202.png",
  "Wago 2273-203 bedugós kötőelem (3 vezetékes)": "images/wago-2273-203.png",
  "Wago 2273-205 bedugós kötőelem (5 vezetékes)": "images/wago-2273-205.png",
  "Érvéghüvely 0,75 mm²": "images/erveghuvely-075.png",
  "Érvéghüvely 1,5 mm²": "images/erveghuvely-15.png",
  "Érvéghüvely 2,5 mm²": "images/erveghuvely-25.png",
  "Érvéghüvely nyomó fogó": "images/erveghuvely-nyomo.png",
  "Kismegszakító 6A B 1P": "images/kismegszakito-16a-b.png",
  "Kismegszakító 10A B 1P": "images/kismegszakito-16a-b.png",
  "Kismegszakító 16A B 1P": "images/kismegszakito-16a-b.png",
  "Kismegszakító 16A C 1P": "images/kismegszakito-16a-c.png",
  "Kismegszakító 16A B 3P": "images/kismegszakito-16a-b-3p.png",
  "MBCu 3x1,5 rézkábel": "images/mbcu-3x15.png",
  "MBCu 3x2,5 rézkábel": "images/mbcu-3x25.png",
  "H07V-U 1,5 mm² vezeték": "images/h07v-u-15.png",
  "H07V-U 2,5 mm² vezeték": "images/h07v-u-25.png",
  "Szigetelőszalag": "images/szigeteloszalag.png",
  "Kapcsoló váltó": "images/kapcsolo-valto.png",
  "LED izzó E27": "images/led-izzo-e27.png",
  "Kombinált fogó": "images/kombinalt-fogo.png",
  "Csavarhúzó készlet (VDE)": "images/csavarhuzo-vde.png",
  "Multiméter": "images/multimeter.png",
  "Fázisceruza": "images/fazisceruza.png",
  "Dugalj süllyesztett": "images/dugalj.png",
  "GEBO javító bilincs 1/2\"": "images/gebo-12.png",
  "GEBO javító bilincs 3/4\"": "images/gebo-34.png",
  "GEBO javító bilincs 1\"": "images/gebo-100.png",
  "Kender (tömítő)": "images/kender.png",
  "Flexibilis csatlakozó 1/2\"": "images/flexi.png",
  "Mosdó szifon": "images/szifon.png",
  "Csaptelep tömítés készlet": "images/csaptelep-tomites.png",
  "Teflonszalag": "images/teflonszalag.png",
  "O-gyűrű készlet": "images/ogyuru.png",
  "Csőfogó": "images/csofogo.png",
  "Svédkulcs": "images/svedkulcs.png",
  "Csővágó": "images/csovago.png",
  "Menetvágó készlet": "images/menetvago.png",
  "WD-40 kenőspray": "images/wd40.png",
  "Gépzsír": "images/gepzsir.png",
  "Univerzális olaj": "images/olaj.png",
  "Saniter szilikon": "images/szaniter-szilikon.png",
  "Fém csőbilincs": "images/csobilincs.png",
  "Kétkomponensű ragasztó": "images/ketkomponensu-ragaszto.png",
  "Csapágy 6204": "images/csapagy-6204.png",
  "Imbusz kulcs készlet": "images/imbusz.png",
  "Akkus fúró-csavarozó": "images/akkus-furo.png",
  "Ékszíj": "images/ekszij.png",
  "Csavar/anya/alátét készlet": "images/csavar-keszlet.png",
  "Szorítógyűrű": "images/szoritogyuru.png",
  "GEBO MB kétrészes javító bilincs (kimenetes)": "images/gebo-mb.png",
  "Menettömítő paszta (Tangit)": "images/menetpaszta.png",
  "Loctite 55 menettömítő zsinór": "images/loctite55.png",
  "Golyóscsap 1/2\"": "images/golyoscsap.png",
  "Kerámia csaptelep betét": "images/csapbetet.png",
  "Perlátor (sugárszabályzó)": "images/perlator.png",
  "Fagyálló/hűtőfolyadék": "images/fagyallo.png",
  "Fűtési inhibitor": "images/inhibitor.png",
  "Szivattyú tengelytömítés (szimmering)": "images/szimmering.png",
  "PE csőhéj szigetelés": "images/pe-csohej.png",
  "Villáskulcs készlet": "images/villaskulcs.png",
  "Vízpumpa fogó": "images/pumpafogo.png",
  "Sarokcsiszoló (flex)": "images/flex.png",
  "Ütvefúró": "images/utvefuro.png",
  "Glett (20 kg)": "images/glett.png",
  "Glettvas": "images/glettvas.png",
  "Javítóhabarcs (25 kg)": "images/javitohabarcs.png",
  "Csemperagasztó (25 kg)": "images/csemperagaszto.png",
  "Fugázó (5 kg)": "images/fugazo.png",
  "Tipli 6 mm": "images/tipli-6.png",
  "Tipli 8 mm": "images/tipli-8.png",
  "Univerzális csavar készlet": "images/csavar.png",
  "Mérőszalag 5 m": "images/meroszalag.png",
  "Vízmérték (libella) 60 cm": "images/vizmertek.png",
  "Kalapács": "images/kalapacs.png",
  "Véső": "images/veso.png",
  "Simító": "images/simito.png",
  "Csiszolóvászon": "images/csiszolovászon.png",
  "Aljzatkiegyenlítő (25 kg)": "images/aljzatkiegyenlito.png",
  "Akril tömítő": "images/akril-tomito.png",
  "Diszperziós falfesték fehér (10 l)": "images/falfestek.png",
  "Zománcfesték (0,75 l)": "images/zomancfestek.png",
  "Alapozó (10 l)": "images/alapozo.png",
  "Hígító": "images/higito.png",
  "Maszkolószalag": "images/maszkoloszalaag.png",
  "Festőhenger": "images/festohenger.png",
  "Ecset készlet": "images/ecset.png",
  "Munkakesztyű": "images/munkakesztyu.png",
  "Védőszemüveg": "images/vedoszemuveg.png",
  "Pillanatragasztó": "images/pillanatragaszto.png",
  "Építési ragasztó": "images/epitesi-ragaszto.png",
  "Univerzális takarítószer": "images/takaritoszer.png",
  "Szemeteszsák (120 l)": "images/szemeteszsak.png",
  "Hypo (klór)": "images/hypo.png",
  "Ablaktisztító": "images/ablaktisztito.png",
  "Porvédő maszk FFP2": "images/ffp2.png",
  "Mikroszálas kendő": "images/mikroszalas.png",
  "LED spot GU10": "images/led-spot-gu10.png",
  "Oldalcsípő fogó": "images/oldalcsipo.png",
  "Műanyag kötődoboz IP54": "images/kotodoboz.png",
  "Spakli készlet": "images/spakli.png",
  "Tipli + facsavar szerelőkészlet": "images/tipli-facsavar.png",
  "FI-relé (áram-védőkapcsoló) 2P 25A 30mA": "images/fi-rele.png",
  "PVC védőcső (gegecső)": "images/gegecso.png",
  "Süllyesztett szerelvénydoboz": "images/szerelvenydoboz.png",
  "Kétpólusú feszültségvizsgáló (DUSPOL)": "images/duspol.png",
  "Villanyszerelő kés (kábeltörő)": "images/kabeltoro.png",
};
